'''
Tenemos la siguiente situación-problema:

“Una empresa de alimentos saludables tiene problemas con la popularidad de sus productos. A pesar de 
ofrecer opciones saludables, muchos clientes se muestran reacios a comprar los productos debido a la 
falta de información sobre los valores nutricionales de las frutas que se utilizan en la producción 
de alimentos”.

Ante esta situación podemos acceder a una API llamada Fruitvice para recopilar información detallada 
sobre los valores nutricionales de las frutas que se utilizan en los productos. Con esta información, 
la empresa podrá actualizar sus empaques y materiales de marketing para resaltar los valores 
nutricionales de las frutas y así atraer más clientes que buscan opciones saludables. Además, la 
empresa puede utilizar la información para desarrollar nuevos productos que satisfagan aún más las 
necesidades nutricionales de su clientela.

Una forma común de acceder a las API es a través de la biblioteca requests. Para eso, también es 
necesario importar el módulo json:


'''
import pandas as pd
import requests
import json

# Los datos de API Fruitvice se obtendrán con la función request.get('url'). Dentro de ella pasamos 
# la dirección API seguida de api/fruit/all para obtener los datos de todas las frutas.
datos_frutas = requests.get('https://fruityvice.com/api/fruit/all')

# Conseguimos recuperar los resultados utilizando la función json.loads(). Para ello es necesario 
# pasar la variable datos_frutas, previamente creada con el atributo text que devuelve el contenido 
# de la respuesta.
resultado = json.loads(datos_frutas.text)

# resultado = json.loads(datos_frutas.text)
print(pd.DataFrame(resultado))

'''
                 name   id  ...         genus                                         nutritions
0            Persimmon   52  ...     Diospyros  {'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'c...
1           Strawberry    3  ...      Fragaria  {'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca...
2               Banana    1  ...          Musa  {'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'c...
3               Tomato    5  ...       Solanum  {'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'ca...
4                 Pear    4  ...         Pyrus  {'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'c...
5               Durian   60  ...         Durio  {'calories': 147, 'fat': 5.3, 'sugar': 6.75, '...
6           Blackberry   64  ...         Rubus  {'calories': 40, 'fat': 0.4, 'sugar': 4.5, 'ca...
7          Lingonberry   65  ...     Vaccinium  {'calories': 50, 'fat': 0.34, 'sugar': 5.74, '...
8                 Kiwi   66  ...       Apteryx  {'calories': 61, 'fat': 0.5, 'sugar': 9.0, 'ca...
9               Lychee   67  ...        Litchi  {'calories': 66, 'fat': 0.44, 'sugar': 15.0, '...
10           Pineapple   10  ...        Ananas  {'calories': 50, 'fat': 0.12, 'sugar': 9.85, '...
11                 Fig   68  ...         Ficus  {'calories': 74, 'fat': 0.3, 'sugar': 16.0, 'c...
12          Gooseberry   69  ...         Ribes  {'calories': 44, 'fat': 0.6, 'sugar': 0.0, 'ca...
13        Passionfruit   70  ...    Passiflora  {'calories': 97, 'fat': 0.7, 'sugar': 11.2, 'c...
14                Plum   71  ...        Prunus  {'calories': 46, 'fat': 0.28, 'sugar': 9.92, '...
15              Orange    2  ...        Citrus  {'calories': 43, 'fat': 0.2, 'sugar': 8.2, 'ca...
16          GreenApple   72  ...         Malus  {'calories': 21, 'fat': 0.1, 'sugar': 6.4, 'ca...
17           Raspberry   23  ...         Rubus  {'calories': 53, 'fat': 0.7, 'sugar': 4.4, 'ca...
18          Watermelon   25  ...     Citrullus  {'calories': 30, 'fat': 0.2, 'sugar': 6.0, 'ca...
19               Lemon   26  ...        Citrus  {'calories': 29, 'fat': 0.3, 'sugar': 2.5, 'ca...
20               Mango   27  ...     Mangifera  {'calories': 60, 'fat': 0.38, 'sugar': 13.7, '...
21           Blueberry   33  ...      Fragaria  {'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca...
22               Apple    6  ...         Malus  {'calories': 52, 'fat': 0.4, 'sugar': 10.3, 'c...
23               Guava   37  ...       Psidium  {'calories': 68, 'fat': 1.0, 'sugar': 9.0, 'ca...
24             Apricot   35  ...        Prunus  {'calories': 15, 'fat': 0.1, 'sugar': 3.2, 'ca...
25               Melon   41  ...       Cucumis  {'calories': 34, 'fat': 0.0, 'sugar': 8.0, 'ca...
26           Tangerine   77  ...        Citrus  {'calories': 45, 'fat': 0.4, 'sugar': 9.1, 'ca...
27            Pitahaya   78  ...     Cactaceae  {'calories': 36, 'fat': 0.4, 'sugar': 3.0, 'ca...
28                Lime   44  ...        Citrus  {'calories': 25, 'fat': 0.1, 'sugar': 1.7, 'ca...
29         Pomegranate   79  ...        Punica  {'calories': 83, 'fat': 1.2, 'sugar': 13.7, 'c...
30         Dragonfruit   80  ...  Selenicereus  {'calories': 60, 'fat': 1.5, 'sugar': 8.0, 'ca...
31               Grape   81  ...         Vitis  {'calories': 69, 'fat': 0.16, 'sugar': 16.0, '...
32               Morus   82  ...         Morus  {'calories': 43, 'fat': 0.39, 'sugar': 8.1, 'c...
33              Feijoa   76  ...    Sellowiana  {'calories': 44, 'fat': 0.4, 'sugar': 3.0, 'ca...
34             Avocado   84  ...        Persea  {'calories': 160, 'fat': 14.66, 'sugar': 0.66,...
35           Kiwifruit   85  ...     Actinidia  {'calories': 61, 'fat': 0.5, 'sugar': 8.9, 'ca...
36           Cranberry   87  ...     Vaccinium  {'calories': 46, 'fat': 0.1, 'sugar': 4.0, 'ca...
37              Cherry    9  ...        Prunus  {'calories': 50, 'fat': 0.3, 'sugar': 8.0, 'ca...
38               Peach   86  ...        Prunus  {'calories': 39, 'fat': 0.25, 'sugar': 8.4, 'c...
39           Jackfruit   94  ...    Artocarpus  {'calories': 95, 'fat': 0.0, 'sugar': 19.1, 'c...
40        Horned Melon   95  ...       Cucumis  {'calories': 44, 'fat': 1.26, 'sugar': 0.5, 'c...
41            Hazelnut   96  ...       Corylus  {'calories': 628, 'fat': 61.0, 'sugar': 4.3, '...
42              Pomelo   98  ...        Citrus  {'calories': 37, 'fat': 0.0, 'sugar': 8.5, 'ca...
43          Mangosteen   99  ...      Garcinia  {'calories': 73, 'fat': 0.58, 'sugar': 16.11, ...
44             Pumpkin  100  ...     Cucurbita  {'calories': 25, 'fat': 0.3, 'sugar': 3.3, 'ca...
45  Japanese Persimmon  101  ...     Diospyros  {'calories': 70, 'fat': 0.2, 'sugar': 13.0, 'c...
46              Papaya   42  ...        Carica  {'calories': 39, 'fat': 0.3, 'sugar': 4.4, 'ca...
47              Annona  103  ...       Annonas  {'calories': 92, 'fat': 0.29, 'sugar': 3.4, 'c...
48   Ceylon Gooseberry  104  ...      Dovyalis  {'calories': 47, 'fat': 0.3, 'sugar': 8.1, 'ca...

[49 rows x 6 columns]


Explicación de Mistral AI:
-------------------------

Explicación del Código
Importar las bibliotecas necesarias:

import pandas as pd: Importa la biblioteca pandas para manipulación y análisis de datos.
import requests: Importa la biblioteca requests para hacer solicitudes HTTP.
import json: Importa el módulo json para manejar datos JSON.
Obtener datos de la API:

datos_frutas = requests.get('https://fruityvice.com/api/fruit/all'): Realiza una solicitud GET a la API de Fruitvice para obtener datos de todas las frutas.
Convertir la respuesta a JSON:

resultado = json.loads(datos_frutas.text): Convierte el texto de la respuesta en un objeto JSON.
Convertir el JSON a un DataFrame de pandas:

print(pd.DataFrame(resultado)): Convierte el objeto JSON en un DataFrame de pandas y lo imprime.
Salida del Código
La salida del código es un DataFrame de pandas que contiene información sobre las frutas, incluyendo su nombre, ID, género, y valores nutricionales (calorías, grasa, azúcar, carbohidratos, proteína, etc.). Aquí hay una explicación de las columnas del DataFrame:

name: Nombre de la fruta.
id: Identificador único de la fruta.
genus: Género de la fruta.
nutritions: Un diccionario que contiene información nutricional de la fruta, incluyendo calorías, grasa, azúcar, carbohidratos, proteína, etc.
Ejemplo de Uso de la Información
Con esta información, la empresa de alimentos saludables puede:

Actualizar sus empaques y materiales de marketing: Resaltar los valores nutricionales de las frutas utilizadas en sus productos para atraer a clientes que buscan opciones saludables.

Desarrollar nuevos productos: Utilizar la información nutricional para crear nuevos productos que satisfagan las necesidades nutricionales de su clientela.

Educar a los clientes: Proporcionar información detallada sobre los beneficios nutricionales de las frutas para ayudar a los clientes a tomar decisiones informadas.

Ejemplo de Código para Acceder a Información Específica
Si deseas acceder a información específica de una fruta, puedes hacerlo de la siguiente manera:
'''
# Acceder a la información nutricional de una fruta específica
nombre_fruta = 'Banana'
informacion_nutricional = next(item for item in resultado if item['name'] == nombre_fruta)['nutritions']
print(f"Información nutricional de {nombre_fruta}: {informacion_nutricional}")


'''
Información nutricional de Banana: {'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'carbohydrates': 22.0, 'protein': 1.0}
'''



